[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.3",
    "pytelegrambotapi>=4.25.0",
    "requests>=2.32.3",
    "schedule>=1.2.2",
    "telegram>=0.0.1",
]
